name = "new-oldnew-mashup"
baseURL = "https://new-oldnew-mashup.wildtechgarden.ca/"
description = "Modules for OldNew Mashup Theme (the new version)"

[module]

[module.hugoVersion]
  min = "0.85.0"
  extended = false

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"
  copyright = "© 2018-2021 Daniel F. Dickinson"
